export const ADD_ANIME = "ADD_ANIME";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const ANIME_LOADED = "ANIME_LOADED";
export const ADD_ANIME_TO_FAV = "ADD_ANIME_TO_FAV";
export const AUTO_COMPLETE_SUGGESTION = "AUTO_COMPLETE_SUGGESTION";
export const CLEAR_AUTO_COMPLETE_SUGGESTION = "CLEAR_AUTO_COMPLETE_SUGGESTION";
export const UPDATE_QUERY = "UPDATE_QUERY";
export const FIND_RECOMMENDATIONS = "FIND_RECOMMENDATIONS";

export const DELETE_ANIME = "DELETE_ANIME";
export const LOAD_ERROR_MSG = "LOAD_ERROR_MSG";
export const CLOSE_ERROR_MSG = "CLOSE_ERROR_MSG";
export const INCREASE_RECOMMENDED_INDEX = "INCREASE_RECOMMENDED_INDEX";
export const DECREASE_RECOMMENDED_INDEX = "DECREASE_RECOMMENDED_INDEX";
export const TOGGLE_FILTER_BUTTON = "TOGGLE_FILTER_BUTTON";
export const UPDATE_GENRE_FILTER_LIST = "UPDATE_GENRE_FILTER_LIST";
export const NO_RECOMMENDATIONS_FOUND = "NO_RECOMMENDATIONS_FOUND";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const LOAD_SPINNER = "LOAD_SPINNER";
export const CLEAR_RECOMMENDATIONS = "CLEAR_RECOMMENDATIONS";
export const FIND_MOVIE_RECOMMENDATIONS = "FIND_MOVIE_RECOMMENDATIONS";
export const FIND_TV_RECOMMENDATIONS = "FIND_TV_RECOMMENDATIONS";
export const FIND_OVA_RECOMMENDATIONS = "FIND_OVA_RECOMMENDATIONS";
export const FIND_ONA_RECOMMENDATIONS = "FIND_ONA_RECOMMENDATIONS";

export const CHANGE_TV_INDEX = "CHANGE_TV_INDEX";
export const CHANGE_MOVIE_INDEX = "CHANGE_MOVIE_INDEX";
export const CHANGE_OVA_INDEX = "CHANGE_OVA_INDEX";
export const CHANGE_ONA_INDEX = "CHANGE_ONA_INDEX";

export const SET_MOBILE_OPEN = "SET_MOBILE_OPEN";

export const LOAD_ANIME_LIST_SPINNER = "LOAD_ANIME_LIST_SPINNER";
export const LOAD_MODAL_SPINNER = "LOAD_MODAL_SPINNER";
export const LOAD_FILTER_SPINNER = "LOAD_FILTER_SPINNER";
export const LOAD_GENRE_SPINNER = "LOAD_GENRE_SPINNER";